//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iLS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _65_653888_plus_symbol_png_green_plus_sign_clipart_transparent__1_ {
            get {
                object obj = ResourceManager.GetObject("65-653888_plus-symbol-png-green-plus-sign-clipart-transparent (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _65_653888_plus_symbol_png_green_plus_sign_clipart_transparent__1_1 {
            get {
                object obj = ResourceManager.GetObject("65-653888_plus-symbol-png-green-plus-sign-clipart-transparent (1)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Blue_and_Red_Colorful_Pharmacy_Store_Promotion_Instagram_Post {
            get {
                object obj = ResourceManager.GetObject("Blue and Red Colorful Pharmacy Store Promotion Instagram Post", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Blue_and_Red_Colorful_Pharmacy_Store_Promotion_Instagram_Post__1_ {
            get {
                object obj = ResourceManager.GetObject("Blue and Red Colorful Pharmacy Store Promotion Instagram Post (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Blue_and_Red_Colorful_Pharmacy_Store_Promotion_Instagram_Post__2_ {
            get {
                object obj = ResourceManager.GetObject("Blue and Red Colorful Pharmacy Store Promotion Instagram Post (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Blue_and_Red_Colorful_Pharmacy_Store_Promotion_Instagram_Post__3_ {
            get {
                object obj = ResourceManager.GetObject("Blue and Red Colorful Pharmacy Store Promotion Instagram Post (3)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Blue_and_Red_Colorful_Pharmacy_Store_Promotion_Instagram_Post__3_1 {
            get {
                object obj = ResourceManager.GetObject("Blue and Red Colorful Pharmacy Store Promotion Instagram Post (3)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Blue_and_White_Clean_and_Geometric_Safety_and_Direction_General_Health_Banner {
            get {
                object obj = ResourceManager.GetObject("Blue and White Clean and Geometric Safety and Direction General Health Banner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Blue_and_White_Clean_and_Geometric_Safety_and_Direction_General_Health_Banner__1_ {
            get {
                object obj = ResourceManager.GetObject("Blue and White Clean and Geometric Safety and Direction General Health Banner (1)" +
                        "", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Blue_and_White_Clean_and_Geometric_Safety_and_Direction_General_Health_Banner__2_ {
            get {
                object obj = ResourceManager.GetObject("Blue and White Clean and Geometric Safety and Direction General Health Banner (2)" +
                        "", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Blue_and_White_Clean_and_Geometric_Safety_and_Direction_General_Health_Banner__2_1 {
            get {
                object obj = ResourceManager.GetObject("Blue and White Clean and Geometric Safety and Direction General Health Banner (2)" +
                        "1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Blue_and_White_Clean_and_Geometric_Safety_and_Direction_General_Health_Banner__3_ {
            get {
                object obj = ResourceManager.GetObject("Blue and White Clean and Geometric Safety and Direction General Health Banner (3)" +
                        "", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Blue_and_White_Clean_and_Geometric_Safety_and_Direction_General_Health_Banner__3_1 {
            get {
                object obj = ResourceManager.GetObject("Blue and White Clean and Geometric Safety and Direction General Health Banner (3)" +
                        "1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Blue_and_White_Clean_and_Geometric_Safety_and_Direction_General_Health_Banner1 {
            get {
                object obj = ResourceManager.GetObject("Blue and White Clean and Geometric Safety and Direction General Health Banner1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Blue_Illustrated_Health_Page_Border {
            get {
                object obj = ResourceManager.GetObject("Blue Illustrated Health Page Border", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Blue_Illustrated_Health_Page_Border__1___1_ {
            get {
                object obj = ResourceManager.GetObject("Blue Illustrated Health Page Border (1) (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Blue_Illustrated_Health_Page_Border__3_ {
            get {
                object obj = ResourceManager.GetObject("Blue Illustrated Health Page Border (3)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Blue_Simple_Minimalist_Medical_Clinic_Youtube_Display_Ad {
            get {
                object obj = ResourceManager.GetObject("Blue Simple Minimalist Medical Clinic Youtube Display Ad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Blue_Simple_Minimalist_Medical_Clinic_Youtube_Display_Ad__1_ {
            get {
                object obj = ResourceManager.GetObject("Blue Simple Minimalist Medical Clinic Youtube Display Ad (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap green_cross_isolated_vector_medical_pharmacy_icon_sign_symbol_medicine_services_flat_care_illustration_first_aid_eps_166199423 {
            get {
                object obj = ResourceManager.GetObject("green-cross-isolated-vector-medical-pharmacy-icon-sign-symbol-medicine-services-f" +
                        "lat-care-illustration-first-aid-eps-166199423", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GreenCross_removebg_preview__1_ {
            get {
                object obj = ResourceManager.GetObject("GreenCross-removebg-preview (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap medical_background_healthcare_technology_flat_260nw_2025416369 {
            get {
                object obj = ResourceManager.GetObject("medical-background-healthcare-technology-flat-260nw-2025416369", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap medical_infographic_banner_background_clinic_pharmacy_laboratory_test_and_research_healthcare_concept_backdrop_illustration_vector {
            get {
                object obj = ResourceManager.GetObject("medical-infographic-banner-background-clinic-pharmacy-laboratory-test-and-researc" +
                        "h-healthcare-concept-backdrop-illustration-vector", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap medicine_backdrop_special_equipment_medical_blue_vertical_background_different_accessories_stethoscope_thermometer_173851139 {
            get {
                object obj = ResourceManager.GetObject("medicine-backdrop-special-equipment-medical-blue-vertical-background-different-ac" +
                        "cessories-stethoscope-thermometer-173851139", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MenuBarICON {
            get {
                object obj = ResourceManager.GetObject("MenuBarICON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_green_cross_in_simple_flat_style_vector_png_image_18575559 {
            get {
                object obj = ResourceManager.GetObject("pngtree-green-cross-in-simple-flat-style-vector-png-image_18575559", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
